### ISSUE TITLE
`entrypoint.sh` always copies `/default-code`

### ISSUE THREAD

**Issue by tom-tan** [wernight/docker-codiad#2]
How to reproduce:
- Run docker with `-v` option to hold the configuration.

```
# docker run --rm -p 8080:80 \
    -e CODIAD_UID=$UID -e CODIAD_GID=$GID \
    -v $PWD/code:/code \
    -v /etc/localtime:/etc/localtime:ro \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    wernight/codiad
```
- Stop and destroy the container.
- Edit `$PWD/code/config.php`. For example, add the following line to `config.php`:

```
define("LANGUAGE", "ja");
```
- Re-run docker with the same arguments and see `config.php`.

Expected: I can find the line `define("LANGUAGE", "ja");`.
Actual: There are no line `define("LANGUAGE", "ja");` because `config.php` is overwritten by `/default-code/config.php`.

The reason is that the statement `[ ! -d '/code/.git' ]` in `entrypoint.sh` always becomes true.
This script expects that there exists `/code/.git` after installing Codiad but  the line `cp -r /default-code/* /code` skip copying `/default-code/.git`.

A simple workaround is just to make a directory `/code/.git` after copying the contents.

**Comment by wernight** [comment]
You're right, there is a bug. I'll see for a fix.

**Comment by wernight** [comment]
Thanks for reporting issues you're having.

You're right on the logic that's in https://github.com/wernight/docker-codiad/blob/master/root/entrypoint.sh however that directectory should exist from https://github.com/wernight/docker-codiad/blob/master/Dockerfile#L58 : `git clone https://github.com/Codiad/Codiad /default-code`. So it should create that `/code/.git` directory.

I have it running but my `/code` contains `.git`.

Before putting a harder fix, I'd like to understand why it's not working as it should. May be you can check that directory content, access rights, or not mounting and `docker exec` in that container to check the content.

**Comment by tom-tan** [comment]
> however that directectory should exist from https://github.com/wernight/docker-codiad/blob/master/Dockerfile#L58 .

`/default-code/.git` exists but it is not copied by `entrypoint.sh` because the wildcard `*` does not match the files and directories which start with `.` in bash, zsh and other shells.

**Comment by wernight** [comment]
Ah of course. Fixing

**Comment by tom-tan** [comment]
I confirmed it works. Thanks!

**Comment by wernight** [comment]
Should be fixed
